name: Deployment

on:
  release:
    types:
      - published

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Make sure only one run is ever queued simultaneously to save resources.
# If a run is queued when one is already queued, the old one will get cancelled before it starts.
concurrency:
  group: "deployment"
  cancel-in-progress: false

jobs:
  library:
    name: Deploy library to Maven Central
    environment:
      name: maven-central
      url: https://central.sonatype.com/artifact/moe.micha/deeplkt
    env:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Publish artifacts to Maven Central
        run: ./gradlew publish --info

  documentation:
    name: Deploy Dokka documentation to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: library
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Generate Dokka documentation
        run: ./gradlew dokkaHtml --info

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'build/dokka/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
